/**
 * @file web.h
 * @brief Web Server HTML Page Definition
 *
 * ESP-IDF compatible web page with joystick control for differential drive chassis
 */

#ifndef WEB_H
#define WEB_H

// ESP-IDF compatible HTML page (no PROGMEM needed)
static const char WEB_PAGE_HTML[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"  <title>Differential Drive Chassis</title>"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"  <style>"
"    body { font-family: Arial, sans-serif; text-align: center; background-color: #f0f0f0; margin: 0; padding: 20px; }"
"    .container { background: white; padding: 20px; margin: 20px auto; max-width: 500px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
"    h1 { color: #333; margin: 10px 0; }"
"    .info { font-size: 14px; color: #666; margin: 5px 0; }"
"    .joystick-area { position: relative; width: 300px; height: 150px; margin: 20px auto; background: linear-gradient(180deg, #e8f5e9 0%, #c8e6c9 100%); border-radius: 10px; border: 3px solid #4caf50; overflow: hidden; }"
"    .joystick-center-line { position: absolute; width: 2px; height: 100%; background: #999; left: 50%; transform: translateX(-50%); }"
"    .joystick-stick { position: absolute; width: 60px; height: 60px; background: #dc3545; border-radius: 50%; top: 50%; left: 50%; transform: translate(-50%, -50%); cursor: pointer; box-shadow: 0 4px 8px rgba(0,0,0,0.3); touch-action: none; }"
"    .joystick-stick:active { background: #c82333; }"
"    .stop-button { padding: 15px 40px; font-size: 18px; background: #ffc107; color: #333; border: none; border-radius: 8px; cursor: pointer; margin: 15px; font-weight: bold; box-shadow: 0 2px 5px rgba(0,0,0,0.2); }"
"    .stop-button:hover { background: #e0a800; }"
"    .stop-button:active { background: #d39e00; transform: scale(0.98); }"
"    .status { font-size: 15px; margin: 8px 0; padding: 8px; background: #f8f9fa; border-radius: 5px; }"
"    .status-label { color: #666; }"
"    .status-value { font-weight: bold; color: #007bff; }"
"    .direction-indicator { font-size: 24px; margin: 10px 0; }"
"    .status-indicator { display: inline-block; width: 20px; height: 20px; border-radius: 50%; margin-left: 10px; vertical-align: middle; transition: all 0.3s ease; }"
"    .status-active { background: #4caf50; box-shadow: 0 0 10px #4caf50; }"
"    .status-inactive { background: #ccc; }"
"    .mode-active { border: 3px solid #4caf50; box-shadow: 0 0 15px rgba(76, 175, 80, 0.3); }"
"    .mode-inactive { border: 1px solid #ddd; }"
"    .mode-label { display: inline-block; padding: 5px 15px; margin: 10px 0; border-radius: 20px; font-size: 14px; font-weight: bold; }"
"    .mode-label-active { background: #4caf50; color: white; }"
"    .mode-label-inactive { background: #e0e0e0; color: #999; }"
"  </style>"
"</head>"
"<body onload=\"initJoystick()\">"
"  <h1>Differential Drive Chassis</h1>"
"  <p class=\"info\">Wheelbase: 160mm | Wheel Diameter: 65mm</p>"
"  <div class=\"container mode-inactive\" id=\"manualContainer\">"
"    <h2>Joystick Control"
"      <span class=\"mode-label mode-label-active\" id=\"manualModeLabel\">ACTIVE</span>"
"    </h2>"
"    <p class=\"info\">Push UP: Forward | Push DOWN: Backward | Left/Right: Turn/Rotate | Max speed 100 RPM</p>"
"    <div class=\"joystick-area\" id=\"joystickArea\">"
"      <div class=\"joystick-center-line\"></div>"
"      <div class=\"joystick-stick\" id=\"joystickStick\"></div>"
"    </div>"
"    <p class=\"direction-indicator\" id=\"directionIndicator\">STOP</p>"
"    <button class=\"stop-button\" onclick=\"emergencyStop()\">EMERGENCY STOP</button>"
"  </div>"
"  <div class=\"container\">"
"    <h2>Chassis Status</h2>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Direction:</span> "
"      <span class=\"status-value\" id=\"statusDirection\">STOP</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Linear Velocity:</span> "
"      <span class=\"status-value\" id=\"statusLinear\">0.000 m/s</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Angular Velocity:</span> "
"      <span class=\"status-value\" id=\"statusAngular\">0.000 rad/s</span>"
"    </div>"
"  </div>"
"  <div class=\"container\">"
"    <h2>Sensor Data (Real-time)</h2>"
"    <div class=\"status\">"
"      <span class=\"status-label\">ToF Front (SD1):</span> "
"      <span class=\"status-value\" id=\"tofFront\">-- mm</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">ToF Left-Front (SD2):</span> "
"      <span class=\"status-value\" id=\"tofLeftFront\">-- mm</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">ToF Left-Rear (SD3):</span> "
"      <span class=\"status-value\" id=\"tofLeftRear\">-- mm</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">IMU Gyro Z (SD4):</span> "
"      <span class=\"status-value\" id=\"imuGyroZ\">-- deg/s</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">IMU Accel X:</span> "
"      <span class=\"status-value\" id=\"imuAccelX\">-- m/s²</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">IMU Accel Y:</span> "
"      <span class=\"status-value\" id=\"imuAccelY\">-- m/s²</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">IMU Temp:</span> "
"      <span class=\"status-value\" id=\"imuTemp\">-- °C</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Left Encoder:</span> "
"      <span class=\"status-value\" id=\"encoderLeft\">-- pulses</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Right Encoder:</span> "
"      <span class=\"status-value\" id=\"encoderRight\">-- pulses</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Vive Sensor 1:</span> "
"      <span class=\"status-value\" id=\"vive1\">--</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Vive Sensor 2:</span> "
"      <span class=\"status-value\" id=\"vive2\">--</span>"
"    </div>"
"  </div>"
"  <div class=\"container mode-inactive\" id=\"wallFollowContainer\">"
"    <h2>Wall Following Mode"
"      <span class=\"status-indicator status-inactive\" id=\"wallFollowIndicator\"></span>"
"      <span class=\"mode-label mode-label-inactive\" id=\"wallFollowModeLabel\">INACTIVE</span>"
"    </h2>"
"    <p class=\"info\">Autonomous wall following using ToF sensors and IMU</p>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Wall Follow State:</span> "
"      <span class=\"status-value\" id=\"wallFollowState\">IDLE</span>"
"    </div>"
"    <button class=\"stop-button\" style=\"background:#4caf50;\" onclick=\"startWallFollow()\">START WALL FOLLOWING</button>"
"    <button class=\"stop-button\" onclick=\"stopWallFollow()\">STOP WALL FOLLOWING</button>"
"  </div>"
"  <div class=\"container mode-inactive\" id=\"navigationContainer\">"
"    <h2>Navigation Map"
"      <span class=\"status-indicator status-inactive\" id=\"navigationIndicator\"></span>"
"      <span class=\"mode-label mode-label-inactive\" id=\"navigationModeLabel\">INACTIVE</span>"
"    </h2>"
"    <p class=\"info\">Click on the map to set navigation goal (144\" x 60\" field)</p>"
"    <canvas id=\"mapCanvas\" width=\"576\" height=\"240\" style=\"border:2px solid #333; cursor:crosshair; background:#fff;\"></canvas>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Robot Position:</span> "
"      <span class=\"status-value\" id=\"robotPos\">--</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Goal Position:</span> "
"      <span class=\"status-value\" id=\"goalPos\">--</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Nav State:</span> "
"      <span class=\"status-value\" id=\"navState\">IDLE</span>"
"    </div>"
"    <button class=\"stop-button\" onclick=\"stopNavigation()\">STOP NAVIGATION</button>"
"  </div>"
"<script>"
"const FIXED_RPM = 100;"
"const MAX_LINEAR_VEL = 0.3;"
"const MAX_ANGULAR_VEL = 1.5;"
"let isDragging = false;"
"let joystickArea, joystickStick;"
"let areaRect, stickRadius;"
"let currentMode = 'MANUAL';"
"let modeSwitching = false;"
"const MODE = {"
"  MANUAL: 'MANUAL',"
"  WALL_FOLLOW: 'WALL_FOLLOW',"
"  NAVIGATION: 'NAVIGATION'"
"};"
"function updateModeUI(newMode) {"
"  const modes = [MODE.MANUAL, MODE.WALL_FOLLOW, MODE.NAVIGATION];"
"  modes.forEach(mode => {"
"    const isActive = (mode === newMode);"
"    let container, label;"
"    if (mode === MODE.MANUAL) {"
"      container = document.getElementById('manualContainer');"
"      label = document.getElementById('manualModeLabel');"
"    } else if (mode === MODE.WALL_FOLLOW) {"
"      container = document.getElementById('wallFollowContainer');"
"      label = document.getElementById('wallFollowModeLabel');"
"    } else if (mode === MODE.NAVIGATION) {"
"      container = document.getElementById('navigationContainer');"
"      label = document.getElementById('navigationModeLabel');"
"    }"
"    if (container && label) {"
"      if (isActive) {"
"        container.className = 'container mode-active';"
"        label.className = 'mode-label mode-label-active';"
"        label.innerText = 'ACTIVE';"
"      } else {"
"        container.className = 'container mode-inactive';"
"        label.className = 'mode-label mode-label-inactive';"
"        label.innerText = 'INACTIVE';"
"      }"
"    }"
"  });"
"  currentMode = newMode;"
"  console.log('Mode switched to:', newMode);"
"}"
"async function switchMode(newMode) {"
"  if (modeSwitching) {"
"    console.log('Mode switch already in progress, ignoring...');"
"    return false;"
"  }"
"  if (currentMode === newMode) {"
"    console.log('Already in mode:', newMode);"
"    return true;"
"  }"
"  modeSwitching = true;"
"  console.log('Switching from', currentMode, 'to', newMode);"
"  try {"
"    if (currentMode === MODE.WALL_FOLLOW) {"
"      await fetch('/stopWallFollow');"
"      await new Promise(resolve => setTimeout(resolve, 100));"
"    }"
"    if (currentMode === MODE.NAVIGATION) {"
"      await fetch('/stopNav');"
"      await new Promise(resolve => setTimeout(resolve, 100));"
"    }"
"    if (currentMode === MODE.MANUAL) {"
"      await fetch('/stopChassis');"
"      await new Promise(resolve => setTimeout(resolve, 100));"
"    }"
"    updateModeUI(newMode);"
"    modeSwitching = false;"
"    return true;"
"  } catch (e) {"
"    console.error('Mode switch error:', e);"
"    modeSwitching = false;"
"    return false;"
"  }"
"}"
"function initJoystick() {"
"  joystickArea = document.getElementById('joystickArea');"
"  joystickStick = document.getElementById('joystickStick');"
"  areaRect = joystickArea.getBoundingClientRect();"
"  stickRadius = joystickStick.offsetWidth / 2;"
"  joystickStick.addEventListener('mousedown', startDrag);"
"  joystickStick.addEventListener('touchstart', startDrag);"
"  document.addEventListener('mousemove', drag);"
"  document.addEventListener('touchmove', drag);"
"  document.addEventListener('mouseup', stopDrag);"
"  document.addEventListener('touchend', stopDrag);"
"  sendVelocity(0, 0);"
"}"
"async function startDrag(e) {"
"  e.preventDefault();"
"  if (currentMode !== MODE.MANUAL) {"
"    const switched = await switchMode(MODE.MANUAL);"
"    if (!switched) return;"
"  }"
"  isDragging = true;"
"}"
"function drag(e) {"
"  if (!isDragging) return;"
"  e.preventDefault();"
"  areaRect = joystickArea.getBoundingClientRect();"
"  let clientX, clientY;"
"  if (e.type.includes('touch')) {"
"    clientX = e.touches[0].clientX;"
"    clientY = e.touches[0].clientY;"
"  } else {"
"    clientX = e.clientX;"
"    clientY = e.clientY;"
"  }"
"  let x = clientX - areaRect.left;"
"  let y = clientY - areaRect.top;"
"  let centerX = areaRect.width / 2;"
"  let centerY = areaRect.height / 2;"
"  let deltaX = x - centerX;"
"  let deltaY = y - centerY;"
"  let maxX = centerX - stickRadius;"
"  let maxY = centerY - stickRadius;"
"  deltaX = Math.max(-maxX, Math.min(maxX, deltaX));"
"  deltaY = Math.max(-maxY, Math.min(maxY, deltaY));"
"  joystickStick.style.left = (centerX + deltaX) + 'px';"
"  joystickStick.style.top = (centerY + deltaY) + 'px';"
"  let normY = -deltaY / maxY;"
"  let normX = deltaX / maxX;"
"  let linear = normY * MAX_LINEAR_VEL;"
"  let angular = -normX * MAX_ANGULAR_VEL;"
"  sendVelocity(linear, angular);"
"  updateStatus(linear, angular);"
"}"
"function stopDrag() {"
"  if (!isDragging) return;"
"  isDragging = false;"
"  joystickStick.style.left = '50%';"
"  joystickStick.style.top = '50%';"
"  sendVelocity(0, 0);"
"  updateStatus(0, 0);"
"}"
"async function emergencyStop() {"
"  isDragging = false;"
"  joystickStick.style.left = '50%';"
"  joystickStick.style.top = '50%';"
"  await fetch('/stopChassis');"
"  await fetch('/stopWallFollow');"
"  await fetch('/stopNav');"
"  updateStatus(0, 0);"
"  updateModeUI(MODE.MANUAL);"
"}"
"function sendVelocity(linear, angular) {"
"  fetch('/setChassisVelocity?linear=' + linear.toFixed(3) + '&angular=' + angular.toFixed(3));"
"}"
"function updateStatus(linear, angular) {"
"  document.getElementById('statusLinear').innerText = linear.toFixed(3) + ' m/s';"
"  document.getElementById('statusAngular').innerText = angular.toFixed(3) + ' rad/s';"
"  let dirText = 'STOP';"
"  if (Math.abs(linear) > 0.01) {"
"    if (linear > 0) {"
"      if (Math.abs(angular) > 0.1) {"
"        dirText = angular > 0 ? 'FORWARD LEFT' : 'FORWARD RIGHT';"
"      } else {"
"        dirText = 'FORWARD';"
"      }"
"    } else {"
"      if (Math.abs(angular) > 0.1) {"
"        dirText = angular > 0 ? 'BACKWARD LEFT' : 'BACKWARD RIGHT';"
"      } else {"
"        dirText = 'BACKWARD';"
"      }"
"    }"
"  } else if (Math.abs(angular) > 0.01) {"
"    dirText = angular > 0 ? 'ROTATE LEFT' : 'ROTATE RIGHT';"
"  }"
"  document.getElementById('directionIndicator').innerText = dirText;"
"  document.getElementById('statusDirection').innerText = dirText;"
"}"
"let mapCanvas, mapCtx;"
"let robotX = -1, robotY = -1, goalX = -1, goalY = -1;"
"let pathPoints = [];"
"function initMap() {"
"  mapCanvas = document.getElementById('mapCanvas');"
"  mapCtx = mapCanvas.getContext('2d');"
"  mapCanvas.addEventListener('click', handleMapClick);"
"  drawMap();"
"  setInterval(updateNavStatus, 500);"
"}"
"function drawMap() {"
"  const scale = 4;"
"  mapCtx.clearRect(0, 0, 576, 240);"
"  mapCtx.fillStyle = '#f0f0f0';"
"  mapCtx.fillRect(0, 0, 576, 240);"
"  mapCtx.strokeStyle = '#333';"
"  mapCtx.lineWidth = 2;"
"  mapCtx.strokeRect(4, 4, 568, 232);"
"  mapCtx.fillStyle = '#2196f3';"
"  mapCtx.fillRect(4, 216, 32, 20);"
"  mapCtx.fillStyle = '#f44336';"
"  mapCtx.fillRect(540, 4, 32, 20);"
"  mapCtx.fillStyle = '#ff9800';"
"  mapCtx.fillRect(160, 60, 32, 24);"
"  mapCtx.fillRect(400, 160, 32, 24);"
"  mapCtx.fillStyle = '#ffeb3b';"
"  mapCtx.fillRect(80, 80, 416, 80);"
"  mapCtx.strokeStyle = '#333';"
"  mapCtx.lineWidth = 2;"
"  mapCtx.strokeRect(80, 80, 416, 2);"
"  mapCtx.strokeRect(80, 158, 416, 2);"
"  if (pathPoints.length > 1) {"
"    mapCtx.strokeStyle = '#00bcd4';"
"    mapCtx.lineWidth = 3;"
"    mapCtx.beginPath();"
"    mapCtx.moveTo(pathPoints[0].x * scale, pathPoints[0].y * scale);"
"    for (let i = 1; i < pathPoints.length; i++) {"
"      mapCtx.lineTo(pathPoints[i].x * scale, pathPoints[i].y * scale);"
"    }"
"    mapCtx.stroke();"
"  }"
"  if (goalX >= 0 && goalY >= 0) {"
"    mapCtx.fillStyle = '#f44336';"
"    mapCtx.beginPath();"
"    mapCtx.arc(goalX * scale, goalY * scale, 8, 0, 2 * Math.PI);"
"    mapCtx.fill();"
"  }"
"  if (robotX >= 0 && robotY >= 0) {"
"    mapCtx.fillStyle = '#4caf50';"
"    mapCtx.beginPath();"
"    mapCtx.arc(robotX * scale, robotY * scale, 6, 0, 2 * Math.PI);"
"    mapCtx.fill();"
"  }"
"}"
"async function handleMapClick(e) {"
"  if (currentMode !== MODE.NAVIGATION) {"
"    const switched = await switchMode(MODE.NAVIGATION);"
"    if (!switched) return;"
"  }"
"  const scale = 4;"
"  const rect = mapCanvas.getBoundingClientRect();"
"  const x = Math.floor((e.clientX - rect.left) / scale);"
"  const y = Math.floor((e.clientY - rect.top) / scale);"
"  goalX = x;"
"  goalY = y;"
"  document.getElementById('goalPos').innerText = '(' + x + ', ' + y + ')';"
"  fetch('/setNavGoal?x=' + x + '&y=' + y);"
"  drawMap();"
"}"
"function updateNavStatus() {"
"  fetch('/getNavStatus')"
"    .then(r => r.json())"
"    .then(data => {"
"      if (data.robot_x !== undefined) {"
"        robotX = data.robot_x;"
"        robotY = data.robot_y;"
"        document.getElementById('robotPos').innerText = '(' + robotX + ', ' + robotY + ')';"
"      }"
"      if (data.state !== undefined) {"
"        document.getElementById('navState').innerText = data.state;"
"        const navIndicator = document.getElementById('navigationIndicator');"
"        if (data.state === 'PLANNING' || data.state === 'NAVIGATING') {"
"          navIndicator.className = 'status-indicator status-active';"
"        } else {"
"          navIndicator.className = 'status-indicator status-inactive';"
"        }"
"      }"
"      if (data.path && data.path.length > 0) {"
"        pathPoints = data.path;"
"      }"
"      drawMap();"
"    })"
"    .catch(e => console.log('Nav status error:', e));"
"}"
"async function stopNavigation() {"
"  await fetch('/stopNav');"
"  if (currentMode === MODE.NAVIGATION) {"
"    updateModeUI(MODE.MANUAL);"
"  }"
"}"
"async function startWallFollow() {"
"  if (currentMode !== MODE.WALL_FOLLOW) {"
"    const switched = await switchMode(MODE.WALL_FOLLOW);"
"    if (!switched) return;"
"  }"
"  try {"
"    const response = await fetch('/startWallFollow');"
"    const data = await response.text();"
"    console.log('Wall follow started:', data);"
"    updateWallFollowStatus();"
"  } catch (e) {"
"    console.log('Start wall follow error:', e);"
"  }"
"}"
"async function stopWallFollow() {"
"  try {"
"    const response = await fetch('/stopWallFollow');"
"    const data = await response.text();"
"    console.log('Wall follow stopped:', data);"
"    updateWallFollowStatus();"
"    if (currentMode === MODE.WALL_FOLLOW) {"
"      updateModeUI(MODE.MANUAL);"
"    }"
"  } catch (e) {"
"    console.log('Stop wall follow error:', e);"
"  }"
"}"
"function updateSensorData() {"
"  fetch('/getSensorData')"
"    .then(r => r.json())"
"    .then(data => {"
"      if (data.tof_front !== undefined) {"
"        document.getElementById('tofFront').innerText = data.tof_front + ' mm';"
"      }"
"      if (data.tof_left_front !== undefined) {"
"        document.getElementById('tofLeftFront').innerText = data.tof_left_front + ' mm';"
"      }"
"      if (data.tof_left_rear !== undefined) {"
"        document.getElementById('tofLeftRear').innerText = data.tof_left_rear + ' mm';"
"      }"
"      if (data.imu_gyro_z !== undefined) {"
"        document.getElementById('imuGyroZ').innerText = data.imu_gyro_z.toFixed(2) + ' deg/s';"
"      }"
"      if (data.imu_accel_x !== undefined) {"
"        document.getElementById('imuAccelX').innerText = data.imu_accel_x.toFixed(2) + ' m/s²';"
"      }"
"      if (data.imu_accel_y !== undefined) {"
"        document.getElementById('imuAccelY').innerText = data.imu_accel_y.toFixed(2) + ' m/s²';"
"      }"
"      if (data.imu_temp !== undefined) {"
"        document.getElementById('imuTemp').innerText = data.imu_temp.toFixed(1) + ' °C';"
"      }"
"      if (data.encoder_left !== undefined) {"
"        document.getElementById('encoderLeft').innerText = data.encoder_left + ' pulses';"
"      }"
"      if (data.encoder_right !== undefined) {"
"        document.getElementById('encoderRight').innerText = data.encoder_right + ' pulses';"
"      }"
"      if (data.vive1_x !== undefined && data.vive1_y !== undefined) {"
"        if (data.vive1_valid) {"
"          document.getElementById('vive1').innerText = 'X=' + data.vive1_x + ', Y=' + data.vive1_y;"
"        } else {"
"          document.getElementById('vive1').innerText = 'No Signal';"
"        }"
"      }"
"      if (data.vive2_x !== undefined && data.vive2_y !== undefined) {"
"        if (data.vive2_valid) {"
"          document.getElementById('vive2').innerText = 'X=' + data.vive2_x + ', Y=' + data.vive2_y;"
"        } else {"
"          document.getElementById('vive2').innerText = 'No Signal';"
"        }"
"      }"
"      if (data.wall_follow_state !== undefined) {"
"        document.getElementById('wallFollowState').innerText = data.wall_follow_state;"
"      }"
"    })"
"    .catch(e => console.log('Sensor data error:', e));"
"}"
"function updateWallFollowStatus() {"
"  fetch('/getWallFollowStatus')"
"    .then(r => r.json())"
"    .then(data => {"
"      if (data.state !== undefined) {"
"        document.getElementById('wallFollowState').innerText = data.state;"
"        const wallIndicator = document.getElementById('wallFollowIndicator');"
"        if (data.is_running === true) {"
"          wallIndicator.className = 'status-indicator status-active';"
"        } else {"
"          wallIndicator.className = 'status-indicator status-inactive';"
"        }"
"      }"
"    })"
"    .catch(e => console.log('Wall follow status error:', e));"
"}"
"window.onload = function() {"
"  initJoystick();"
"  initMap();"
"  updateModeUI(MODE.MANUAL);"
"  setInterval(updateSensorData, 500);"
"  setInterval(updateWallFollowStatus, 1000);"
"};"
"</script>"
"</body>"
"</html>";

#endif // WEB_H