/**
 * @file web.h
 * @brief Web Server HTML Page Definition
 *
 * ESP-IDF compatible web page with joystick control for differential drive chassis
 */

#ifndef WEB_H
#define WEB_H

// ESP-IDF compatible HTML page (no PROGMEM needed)
static const char WEB_PAGE_HTML[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"  <title>Differential Drive Chassis</title>"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"  <style>"
"    body { font-family: Arial, sans-serif; text-align: center; background-color: #f0f0f0; margin: 0; padding: 20px; }"
"    .container { background: white; padding: 20px; margin: 20px auto; max-width: 500px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }"
"    h1 { color: #333; margin: 10px 0; }"
"    .info { font-size: 14px; color: #666; margin: 5px 0; }"
"    .joystick-area { position: relative; width: 300px; height: 150px; margin: 20px auto; background: linear-gradient(180deg, #e8f5e9 0%, #c8e6c9 100%); border-radius: 10px; border: 3px solid #4caf50; overflow: hidden; }"
"    .joystick-center-line { position: absolute; width: 2px; height: 100%; background: #999; left: 50%; transform: translateX(-50%); }"
"    .joystick-stick { position: absolute; width: 60px; height: 60px; background: #dc3545; border-radius: 50%; top: 50%; left: 50%; transform: translate(-50%, -50%); cursor: pointer; box-shadow: 0 4px 8px rgba(0,0,0,0.3); touch-action: none; }"
"    .joystick-stick:active { background: #c82333; }"
"    .stop-button { padding: 15px 40px; font-size: 18px; background: #ffc107; color: #333; border: none; border-radius: 8px; cursor: pointer; margin: 15px; font-weight: bold; box-shadow: 0 2px 5px rgba(0,0,0,0.2); }"
"    .stop-button:hover { background: #e0a800; }"
"    .stop-button:active { background: #d39e00; transform: scale(0.98); }"
"    .status { font-size: 15px; margin: 8px 0; padding: 8px; background: #f8f9fa; border-radius: 5px; }"
"    .status-label { color: #666; }"
"    .status-value { font-weight: bold; color: #007bff; }"
"    .direction-indicator { font-size: 24px; margin: 10px 0; }"
"  </style>"
"</head>"
"<body onload=\"initJoystick()\">"
"  <h1>Differential Drive Chassis</h1>"
"  <p class=\"info\">Wheelbase: 160mm | Wheel Diameter: 65mm</p>"
"  <div class=\"container\">"
"    <h2>Joystick Control</h2>"
"    <p class=\"info\">Push UP: Forward | Push DOWN: Backward | Left/Right: Turn/Rotate | Max speed 100 RPM</p>"
"    <div class=\"joystick-area\" id=\"joystickArea\">"
"      <div class=\"joystick-center-line\"></div>"
"      <div class=\"joystick-stick\" id=\"joystickStick\"></div>"
"    </div>"
"    <p class=\"direction-indicator\" id=\"directionIndicator\">STOP</p>"
"    <button class=\"stop-button\" onclick=\"emergencyStop()\">EMERGENCY STOP</button>"
"  </div>"
"  <div class=\"container\">"
"    <h2>Chassis Status</h2>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Direction:</span> "
"      <span class=\"status-value\" id=\"statusDirection\">STOP</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Linear Velocity:</span> "
"      <span class=\"status-value\" id=\"statusLinear\">0.000 m/s</span>"
"    </div>"
"    <div class=\"status\">"
"      <span class=\"status-label\">Angular Velocity:</span> "
"      <span class=\"status-value\" id=\"statusAngular\">0.000 rad/s</span>"
"    </div>"
"  </div>"
"<script>"
"const FIXED_RPM = 100;"
"const MAX_LINEAR_VEL = 0.3;"
"const MAX_ANGULAR_VEL = 1.5;"
"let isDragging = false;"
"let joystickArea, joystickStick;"
"let areaRect, stickRadius;"
"function initJoystick() {"
"  joystickArea = document.getElementById('joystickArea');"
"  joystickStick = document.getElementById('joystickStick');"
"  areaRect = joystickArea.getBoundingClientRect();"
"  stickRadius = joystickStick.offsetWidth / 2;"
"  joystickStick.addEventListener('mousedown', startDrag);"
"  joystickStick.addEventListener('touchstart', startDrag);"
"  document.addEventListener('mousemove', drag);"
"  document.addEventListener('touchmove', drag);"
"  document.addEventListener('mouseup', stopDrag);"
"  document.addEventListener('touchend', stopDrag);"
"  sendVelocity(0, 0);"
"}"
"function startDrag(e) {"
"  isDragging = true;"
"  e.preventDefault();"
"}"
"function drag(e) {"
"  if (!isDragging) return;"
"  e.preventDefault();"
"  areaRect = joystickArea.getBoundingClientRect();"
"  let clientX, clientY;"
"  if (e.type.includes('touch')) {"
"    clientX = e.touches[0].clientX;"
"    clientY = e.touches[0].clientY;"
"  } else {"
"    clientX = e.clientX;"
"    clientY = e.clientY;"
"  }"
"  let x = clientX - areaRect.left;"
"  let y = clientY - areaRect.top;"
"  let centerX = areaRect.width / 2;"
"  let centerY = areaRect.height / 2;"
"  let deltaX = x - centerX;"
"  let deltaY = y - centerY;"
"  let maxX = centerX - stickRadius;"
"  let maxY = centerY - stickRadius;"
"  deltaX = Math.max(-maxX, Math.min(maxX, deltaX));"
"  deltaY = Math.max(-maxY, Math.min(maxY, deltaY));"
"  joystickStick.style.left = (centerX + deltaX) + 'px';"
"  joystickStick.style.top = (centerY + deltaY) + 'px';"
"  let normY = -deltaY / maxY;"
"  let normX = deltaX / maxX;"
"  let linear = normY * MAX_LINEAR_VEL;"
"  let angular = -normX * MAX_ANGULAR_VEL;"
"  sendVelocity(linear, angular);"
"  updateStatus(linear, angular);"
"}"
"function stopDrag() {"
"  if (!isDragging) return;"
"  isDragging = false;"
"  joystickStick.style.left = '50%';"
"  joystickStick.style.top = '50%';"
"  sendVelocity(0, 0);"
"  updateStatus(0, 0);"
"}"
"function emergencyStop() {"
"  isDragging = false;"
"  joystickStick.style.left = '50%';"
"  joystickStick.style.top = '50%';"
"  fetch('/stopChassis');"
"  updateStatus(0, 0);"
"}"
"function sendVelocity(linear, angular) {"
"  fetch('/setChassisVelocity?linear=' + linear.toFixed(3) + '&angular=' + angular.toFixed(3));"
"}"
"function updateStatus(linear, angular) {"
"  document.getElementById('statusLinear').innerText = linear.toFixed(3) + ' m/s';"
"  document.getElementById('statusAngular').innerText = angular.toFixed(3) + ' rad/s';"
"  let dirText = 'STOP';"
"  if (Math.abs(linear) > 0.01) {"
"    if (linear > 0) {"
"      if (Math.abs(angular) > 0.1) {"
"        dirText = angular > 0 ? 'FORWARD LEFT' : 'FORWARD RIGHT';"
"      } else {"
"        dirText = 'FORWARD';"
"      }"
"    } else {"
"      if (Math.abs(angular) > 0.1) {"
"        dirText = angular > 0 ? 'BACKWARD LEFT' : 'BACKWARD RIGHT';"
"      } else {"
"        dirText = 'BACKWARD';"
"      }"
"    }"
"  } else if (Math.abs(angular) > 0.01) {"
"    dirText = angular > 0 ? 'ROTATE LEFT' : 'ROTATE RIGHT';"
"  }"
"  document.getElementById('directionIndicator').innerText = dirText;"
"  document.getElementById('statusDirection').innerText = dirText;"
"}"
"</script>"
"</body>"
"</html>";

#endif // WEB_H